pg_backup:
  build: .
  volumes:
    - ./backups:/backups
    - ./config:/config
  environment:
    - POSTGRES_HOSTNAME=localhost
    - POSTGRES_USER=postgres
    - POSTGRES_PASS=K93SD8yEDaVXRpkvFtCj
    - WEEKS_TO_KEEP=4
    - DAYS_TO_KEEP=7
    - DAY_OF_WEEK_TO_KEEP=6
    - CRON_RUN_MINUTE=0
    - CRON_RUN_HOUR=23
    - RCLONE_REMOTE_NAME=backblaze
    - RCLONE_REMOTE_PATH=Dionysus-Postgres